### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #3

### ISSUE THREAD

**Issue by iRYO400** [Yalantis/uCrop#103]
Hi! 
I get this when I click "CROP RANDOM IMAGE". 
Copied with all values your sample to my project and still get the same error

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                                Process: com.r400.ultra.free.rwallpapers, PID: 3015
                                                                                java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                    at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient;
                                                                                    at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:208)
                                                                                    at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:157)
                                                                                    at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:84)
                                                                                    at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:40)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 
                                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.OkHttpClient" on path: DexPathList[[dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-support-annotations-23.3.0_1f7151a7143fc8b474ffb58860331b37fd019135-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-picasso-2.5.2_4659f664220ba1f44941f3df8eea2ba05c46c12d-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-library-2.4.0_f197cb68cee73f016d91066f2402594f0155f631-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-kenburnsview-1.0.6_0a7ff3d4d5d5b17b865ac5e61fcce292d290f2a6-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-internal_impl-23.3.0_916487d86e431b0ecdaefc460ac294d2b10b0ca2-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-gson-2.4_e7c76fbc098505750e3c3ff30b38d2cc5adcbf9e-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-glide-3.7.0_10f434a49838b9cc36a3571b7a4972d8e110086f-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.yalantis-ucrop-2.0.0_dda1f6bca2b138472aa7c304fb1596afd0f7b850-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.jpardogo.materialtabstrip-library-1.1.0_06931e1f0912e09678394df98958fb76b95d472a-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.isseiaoki-simplecropview-1.1.0_70bc7243a1e29de960051a9ffdeba8d305335a25-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.google.android.gms-pl
05-04 10:53:44.613 3015-3015/com.r400.ultra.free.rwallpapers E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices
05-04 10:56:28.673 12925-13835/com.r400.ultra.free.rwallpapers E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                 Process: com.r400.ultra.free.rwallpapers, PID: 12925
                                                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient;
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:208)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:157)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:84)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:40)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.OkHttpClient" on path: DexPathList[[dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-support-annotations-23.3.0_1f7151a7143fc8b474ffb58860331b37fd019135-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-picasso-2.5.2_4659f664220ba1f44941f3df8eea2ba05c46c12d-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-library-2.4.0_f197cb68cee73f016d91066f2402594f0155f631-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-kenburnsview-1.0.6_0a7ff3d4d5d5b17b865ac5e61fcce292d290f2a6-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-internal_impl-23.3.0_916487d86e431b0ecdaefc460ac294d2b10b0ca2-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-gson-2.4_e7c76fbc098505750e3c3ff30b38d2cc5adcbf9e-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-glide-3.7.0_10f434a49838b9cc36a3571b7a4972d8e110086f-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.yalantis-ucrop-2.0.0_dda1f6bca2b138472aa7c304fb1596afd0f7b850-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.jpardogo.materialtabstrip-library-1.1.0_06931e1f0912e09678394df98958fb76b95d472a-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.isseiaoki-simplecropview-1.1.0_70bc7243a1e29de960051a9ffdeba8d305335a25-classes.dex", dex file "/data/data/com.r400.ultra.free.rwallpapers/files/instant-run/dex/slice-com.google.android.gms-p
05-04 10:56:28.793 12925-12925/com.r400.ultra.free.rwallpapers E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices
```

Also I override `ucrop_color_toolbar_widget` in colors.xml
`<color tools:override = "true" name="ucrop_color_toolbar_widget">@color/slide_1</color>`

Dependencies
```
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.github.florent37:materialviewpager:1.1.3') {
        transitive = true
    }
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.isseiaoki:simplecropview:1.1.0'
    compile 'com.yalantis:ucrop:2.0.0@aar'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.volley:volley:1.0.0'
```

**Comment by shliama** [comment]
Okay, so can you check whether you have two okhttp libraries (maybe other libraries/modules have dependency?)
Do you have multidex enabled?
What about proguard?

**Comment by iRYO400** [comment]
MaterialViewPager uses Picasso that uses okhttp 
![inside](https://cloud.githubusercontent.com/assets/12654767/15033605/52815e4a-128e-11e6-86ba-f2edb18a0fa5.png)

Multidex enabled
```
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 9
        multiDexEnabled true
        versionName "2.0"
    }
```

And I dont use proguard

**Comment by shliama** [comment]
That's strange, because this is how my libraries list looks like when I have your dependencies list added to sample
<img width="306" alt="1" src="https://cloud.githubusercontent.com/assets/2311626/15040409/4289b558-12bd-11e6-9ef0-25c1db5d5cc0.png">

Maybe you should just make "Clean" for you project?

**Comment by shliama** [comment]
@iRYO400 I could fix it with this

```gradle
compile ('com.yalantis:ucrop:2.0.0@aar')  {
    transitive = true
}
```

**Comment by iRYO400** [comment]
@shliama I've found solution!
As you said I made this
```
compile ('com.yalantis:ucrop:2.0.0@aar')  {
    transitive = true //still don't know what it does
}
```
after that okhttp and okio appeared. 
Then I upgraded Android Studio from 2.0 to 2.1 and AStudio asked me about upgrading Gradle, I clicked "yes"
...
PROFIT! 
Thank you very much!

**Comment by mr-sarsarabi** [comment]
@shliama 
Hi,
I've Had the same issue with this library and i just used this code that you provided and it worked.
But I guess that this is not the last version.
The thing is I've encountered a bug while cropping a panorama image with the aspect ratio 1:1.
the result was the panorama photo just rotated 90 degrees instead of the cropped photo.
I don't know if this is fixed in newer versions or not
