### ISSUE TITLE
FileUtils.java accesses undefined column _data

### ISSUE THREAD

**Issue by chrisdoc** [Yalantis/uCrop#104]
Commit _Fixed resize logic for cropping original images_ 9f13185665115dca8bd6603a256b7528fa81a7cf introduces a new FileUtils.java helper that tries to access the column `_data` of a MediaStore which results in a thrown IllegalArgumentException because the exception is not catched.

Test devices:
- Moto G2, Android 6.0, uCrop 2.0.0
- Nexus 5X, Android N, uCrop 2.0.0

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
        at com.yalantis.ucrop.util.FileUtils.getDataColumn(FileUtils.java:224)
        at com.yalantis.ucrop.util.FileUtils.getPath(FileUtils.java:315)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:163)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:84)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:40)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by shliama** [comment]
Strange, I haven't received any of that yet on my projects. But I'll add fix in the next patch.

**Comment by chrisdoc** [comment]
Any progress @shliama

**Comment by shliama** [comment]
@chrisdoc please try to use library version 2.1.0. 
Above exception now should be caught properly.

**Comment by yukuku** [comment]
When accessing content uri, you should not try to get the path of the actual file. So you don't need read external storage permissions.

**Comment by CeccoCQ** [comment]
I've the v2.1 and still have the error.

**Comment by shliama** [comment]
It crashes the app? I've added catch clause for this exception but it goes to logs.

**Comment by IbraTq** [comment]
i have the v2.2 and still have the error
please check this:

http://crashes.to/s/edce6405f76
