### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by small-dream** [Yalantis/uCrop#12]
I am just run the simple,and get the exception,log as follow:

01-28 14:24:59.110 31033-31033/com.yalantis.ucrop.sample E/SampleActivity: handleCropError: 
                                                                           java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@420cfd18
                                                                               at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1093)
                                                                               at android.graphics.Canvas.drawBitmap(Canvas.java:1179)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:646)
                                                                               at com.yalantis.ucrop.view.CropImageView.cropImage(CropImageView.java:134)
                                                                               at com.yalantis.ucrop.UCropActivity.cropAndSaveImage(UCropActivity.java:381)
                                                                               at com.yalantis.ucrop.UCropActivity.onOptionsItemSelected(UCropActivity.java:81)

**Comment by shliama** [comment]
Thanks for the report.
Issue should be fixed in the next update 1.1.1.
