### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by iielse** [Yalantis/uCrop#157]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> D:\ASProjectsWorkspace\MyApplication\app\build\intermediates\exploded-aar\com.yalantis\ucrop\2.0.0\res\drawable\ucrop_vector_loader.xml: Error: Width (0) and height (0) cannot be <= 0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.028 secs
```

------------------------------
**my build.gradle**

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "org.ielse.querypic"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'

    compile 'com.yalantis:ucrop:2.0.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
}
```

what should i do

**Comment by erkangur** [comment]
I encountered same issue and solved it as follows: 
In your build.gradle put
```
defaultConfig {
   ...
   generatedDensities = []
}

aaptOptions {
    ...
    additionalParameters "--no-version-vectors"
}
```

But this causes problems I guess, below <= API 19 devices, i got following errors: 

```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
E/AndroidRuntime( 5351): 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
E/AndroidRuntime( 5351): 	at android.content.res.Resources.getDrawable(Resources.java:700)
E/AndroidRuntime( 5351): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
E/AndroidRuntime( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
E/AndroidRuntime( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
E/AndroidRuntime( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
E/AndroidRuntime( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
E/AndroidRuntime( 5351): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
E/AndroidRuntime( 5351): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/AndroidRuntime( 5351): 	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:104)
E/AndroidRuntime( 5351): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 5351): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 5351): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
```

and 

```
E/VdcInflateDelegate( 5351): Exception while inflating <vector>
E/VdcInflateDelegate( 5351): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate( 5351): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
E/VdcInflateDelegate( 5351): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
E/VdcInflateDelegate( 5351): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
E/VdcInflateDelegate( 5351): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
E/VdcInflateDelegate( 5351): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/VdcInflateDelegate( 5351): 	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:104)
E/VdcInflateDelegate( 5351): 	at android.app.Activity.performCreate(Activity.java:5231)
E/VdcInflateDelegate( 5351): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/VdcInflateDelegate( 5351): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/VdcInflateDelegate( 5351): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/VdcInflateDelegate( 5351): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/VdcInflateDelegate( 5351): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/VdcInflateDelegate( 5351): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate( 5351): 	at android.os.Looper.loop(Looper.java:136)
E/VdcInflateDelegate( 5351): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/VdcInflateDelegate( 5351): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate( 5351): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate( 5351): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/VdcInflateDelegate( 5351): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
```

**Comment by iielse** [comment]
This is useful.
Thank you very much.
