### ISSUE TITLE
can you add armeabi native code?

### ISSUE THREAD

**Issue by olivercm** [Yalantis/uCrop#159]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
crop crash

**What is the expected behavior?**
crop fine

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
we use [fresco](https://github.com/facebook/fresco) also, and it's APP_ABI include [armeabi-v7a armeabi arm64-v8a x86 x86_64](https://github.com/facebook/fresco/blob/master/animated-gif/src/main/jni/Application.mk), uCrop does not have armeabi. So if cpu architecture is arm and not  armeabi-v7a or arm64-v8a, uCrop will crash.

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/[package name]-1/base.apk"],nativeLibraryDirectories=[/data/app/[package name]-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libucrop.so"
   at java.lang.Runtime.loadLibrary(Runtime.java:366)
   at java.lang.System.loadLibrary(System.java:988)
   at com.yalantis.ucrop.task.BitmapCropTask.<clinit>(BitmapCropTask.java:35)
   at com.yalantis.ucrop.view.CropImageView.cropAndSaveImage(CropImageView.java:85)
   at com.yalantis.ucrop.UCropActivity.cropAndSaveImage(UCropActivity.java:601)
   at com.yalantis.ucrop.UCropActivity.onOptionsItemSelected(UCropActivity.java:155)
   at android.app.Activity.onMenuItemSelected(Activity.java:2955)
   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403)
   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:189)
   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
   at android.view.View.performClick(View.java:4909)
   at android.view.View$PerformClick.run(View.java:20390)
   at android.os.Handler.handleCallback(Handler.java:815)
   at android.os.Handler.dispatchMessage(Handler.java:104)
   at android.os.Looper.loop(Looper.java:194)
   at android.app.ActivityThread.main(ActivityThread.java:5803)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
uCrop version 2.1.1

**Comment by shliama** [comment]
Hi @olivercm.
Wasn't sure if someone still needs armeabi/mips support but it's not a big problem to add it :octocat: 
Version 2.1.2 with armeabi support should be available in about 30 minutes.

**Comment by olivercm** [comment]
thanks
