### ISSUE TITLE
BUT: FileNotFoundException: Permission denied

### ISSUE THREAD

**Issue by Montrazul** [Yalantis/uCrop#168]
I want to report a bug.

When i pick a picture from the gallery and put this as source uri into `UCrop.of()` the following exception is thrown:

`
E/TransformImageView: onFailure: setImageUri
                                                                           java.io.FileNotFoundException: Permission denied
                                                                               at android.os.Parcel.openFileDescriptor(Native Method)
                                                                               at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
                                                                               at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
                                                                               at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:937)
                                                                               at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:795)
                                                                               at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:749)
                                                                               at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:97)
                                                                               at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
`

The expected behaviour ofcourse would be to crop the image and return the target uri.
Im on Android 6.0 with UCrop version 2.1.2. I have never used UCrop before.

**Comment by Montrazul** [comment]
Related to Android 6.0 permissions. Grant storage permissions to the user and everything is fine.
