### ISSUE TITLE
Transparency turns into black

### ISSUE THREAD

**Issue by damianpiwowarski** [Yalantis/uCrop#182]
There is a problem with saving transparency properly. If you will import image with transparency and you will leave it without any move - transparency is saved because original image is used as cropped bitmap. But any movement that causes to use croping itself makes transparency turn black. 

Turning PNG compression could help, but library returns an error:

`08-26 18:17:58.350 30465-31126/? W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
                                                  java.io.IOException: Invalid marker: 89
                                                      at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1830)
                                                      at android.media.ExifInterface.loadAttributes(ExifInterface.java:1474)
                                                      at android.media.ExifInterface.<init>(ExifInterface.java:1111)
                                                      at com.yalantis.ucrop.util.ImageHeaderParser.copyExif(ImageHeaderParser.java:404)
                                                      at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:144)
                                                      at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:88)
                                                      at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:30)
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                      at java.lang.Thread.run(Thread.java:761)`

**Comment by shliama** [comment]
Hello @damianpiwowarski  and thanks for the issue. Indeed, there was a problem with ExifInterface and PNG images. I've already implemented a fix, so you can turn on PNG compression without errors. It will be available in the next library version soon!

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```

**Comment by Mahan3340** [comment]
compile 'com.yalantis:ucrop:2.2.0'  this is not working , when I try to replace this with the old one the method " option.setOvalDimmedLayer() " is not found

**Comment by shliama** [comment]
@Mahan3340 please use `option.setCircleDimmedLayer()`

**Comment by Mahan3340** [comment]
thanks for your quick reply , it sounds werid but I solved it by using both compile 'com.yalantis:ucrop:2.2.0'
    compile 'com.yalantis:ucrop:2.0.0' together

**Comment by ChenSiLiang** [comment]
I have the same problem and I try the solutions above.
it work.
but in some situation,some files end with .JPG but actually is a PNG.
so, I can only set 
` crop.setCompressionFormat(Bitmap.CompressFormat.PNG);`
and compile 'com.yalantis:ucrop:2.2.0'
the crop pictures don't need exif infomations in my opinion.

**Comment by TeeRawk** [comment]
resolved
