### ISSUE TITLE
Matrix NPE on newly set image

### ISSUE THREAD

**Issue by NewColours** [Yalantis/uCrop#255]
Bug

The following exception is thrown when touching newly set image
`java.lang.NullPointerException: Attempt to get length of null array
                      at android.graphics.Matrix.mapPoints(Matrix.java:672)
                      at com.yalantis.ucrop.view.TransformImageView.updateCurrentImagePoints(TransformImageView.java:335)
                      at com.yalantis.ucrop.view.TransformImageView.setImageMatrix(TransformImageView.java:199)
                      at com.yalantis.ucrop.view.TransformImageView.postTranslate(TransformImageView.java:220)
                      at com.yalantis.ucrop.view.GestureCropImageView$GestureListener.onScroll(GestureCropImageView.java:136)
                      at android.view.GestureDetector.onTouchEvent(GestureDetector.java:654)
                      at com.yalantis.ucrop.view.GestureCropImageView.onTouchEvent(GestureCropImageView.java:80)
                      at android.view.View.dispatchTouchEvent(View.java:9349)`

Touching the image in the following sample application, before the System UI becomes hidden will trigger the bug: https://github.com/NewColours/ReproductionApplication

This bug has been replicable on all devices tested. Primarily tested on Android 6.0 (Marshmallow)

**Comment by Sirelon** [comment]
same crash was when set to view setImageURI() 
just change to setImageUri(uri, outputUri) and everything works fine.

**Comment by NewColours** [comment]
Thanks, I'll try it. I'm not outputting anything, I just want the image to be manipulable but this might be a workaround if it works

**Comment by NewColours** [comment]
I currently download and later load using Glide (so I don't explicitly know the Uri) and thus I do a Glide load and then setImageDrawable. 

Using setImageUri(uri, outputUri) means I can't load via glide. Please update me when there is a better solution

**Comment by TeeRawk** [comment]
Hi , @NewColours  , so am I getting it right. You're downloading the image from the internet via link, and then want to crop it with  ucrop , is that right ?

**Comment by NewColours** [comment]
Actually, I never crop and export the image. I just use the view for its great pinch/rotate functionality. Exactly as in the sample app. Yes I have the image downloaded in advance.

**Comment by ciprig** [comment]
Same crash we have reported in Crashlytics 23times version 2.2.0 image source is phone camera
Android: 6.0 and 6.0.1
Devices: LGE v10, Samsung Galaxy Note5, TCL 5056N, ZTE Grand X Max 2

Stacktrace: 
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at android.graphics.Matrix.mapPoints(Matrix.java:672)
       at com.yalantis.ucrop.view.TransformImageView.updateCurrentImagePoints(TransformImageView.java:335)
       at com.yalantis.ucrop.view.TransformImageView.setImageMatrix(TransformImageView.java:199)
       at com.yalantis.ucrop.view.TransformImageView.postTranslate(TransformImageView.java:220)
       at com.yalantis.ucrop.view.GestureCropImageView$GestureListener.onScroll(GestureCropImageView.java:136)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:607)
       at com.yalantis.ucrop.view.GestureCropImageView.onTouchEvent(GestureCropImageView.java:80)
       at android.view.View.dispatchTouchEvent(View.java:9307)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2296)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2422)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1754)
       at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1754)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2383)
       at android.view.View.dispatchPointerEvent(View.java:9527)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4416)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4282)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3786)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3786)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3879)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3936)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3786)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6140)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6114)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6075)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6272)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6222)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6295)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:600)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by Gongcong** [comment]
I use setImageUri(uri, outputUri),alse crash.

**Comment by AleksIakushev** [comment]
Hi all,

I used setImageUri(uri, outputUri) and it works fine in most cases, but have NPE with following case:
1) open a picture with high resolution(for example 8000x4000)
2) when loading try to touch many times.

Do you have a new recommendations how to resolve that?

**Comment by AleksIakushev** [comment]
Tried to overload setImageMatrix method. Seems work correctly:

public void setImageMatrix(Matrix matrix) {
        if (mBitmapLaidOut) super.setImageMatrix(matrix);
}

**Comment by parcool** [comment]
crash crash crash..................

**Comment by amd110** [comment]
Is the problem still unresolved?

**Comment by rovkinmax** [comment]
I solve the problem with override setImageMatrix method:

```
class CustomCropImageView(context: Context?) : GestureCropImageView(context) {

    private var tempMatrix: Matrix? = null

    override fun setImageMatrix(matrix: Matrix?) {
        try {
            tempMatrix = matrix
            if (mBitmapLaidOut)
                super.setImageMatrix(matrix)
        } catch (e: Exception) {
        }
    }


    override fun onImageLaidOut() {
        super.onImageLaidOut()
        imageMatrix = tempMatrix
    }
}
```

**Comment by monsterbrain** [comment]
> I solve the problem with override setImageMatrix method:
> 
> ```
> class CustomCropImageView(context: Context?) : GestureCropImageView(context) {
> 
>     private var tempMatrix: Matrix? = null
> 
>     override fun setImageMatrix(matrix: Matrix?) {
>         try {
>             tempMatrix = matrix
>             if (mBitmapLaidOut)
>                 super.setImageMatrix(matrix)
>         } catch (e: Exception) {
>         }
>     }
> 
> 
>     override fun onImageLaidOut() {
>         super.onImageLaidOut()
>         imageMatrix = tempMatrix
>     }
> }
> ```

How to override the GestureCropImageView ..? I cannot access the variable, nor extends the Ucrop ? Any ideas ..

**Comment by smileToWxm** [comment]
you can setTransformImageListener() , onLoadComplete() Indicates that the picture is loaded， you can  Handle your logic

**Comment by monsterbrain** [comment]
@smileToWxm The above crash will still occur.

One Solution we did was, without overriding the GestureCropImageView

1. add an empty/transparent clickable view over the Ucrop View
2. Make it invisible (ie allow clicks) only on **onLoadComplete** using **setTransformImageListener**

This way the user clicks during the image loading will be blocked.
