### ISSUE TITLE
in android 7.0 can not open FileProvider uri

### ISSUE THREAD

**Issue by a251115100** [Yalantis/uCrop#260]
java.io.FileNotFoundException: No such file or directory
                                                                           at android.os.Parcel.openFileDescriptor(Native Method)
                                                                           at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
                                                                           at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
                                                                           at android.support.v4.content.FileProvider.openFile(SourceFile:544)
                                                                           at android.content.ContentProvider.openAssetFile(ContentProvider.java:1322)
                                                                           at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1502)
                                                                           at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1568)
                                                                           at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:391)
                                                                           at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1091)
                                                                           at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:932)
                                                                           at android.content.ContentResolver.openInputStream(ContentResolver.java:657)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(SourceFile:198)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(SourceFile:176)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(SourceFile:90)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(SourceFile:41)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:833)

**Comment by moslem-deris** [comment]
I have the same problem on Android 21
