### ISSUE TITLE
Unable to start activity 

### ISSUE THREAD

**Issue by Hitexroid** [Yalantis/uCrop#273]
`UCrop.of(Uri.fromFile(new File(In)), Uri.fromFile(new File(Out)))
     .withAspectRatio(1, 1)
     .withMaxResultSize(maxWidth, maxHeight)
     .start(activity);`

`<activity
android:name="com.yalantis.ucrop.UCropActivity"
android:screenOrientation="portrait"
android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>`

**Error :** 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{b4a.example/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class com.yalantis.ucrop.view.widget.AspectRatioTextView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class com.yalantis.ucrop.view.widget.AspectRatioTextView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.yalantis.ucrop.UCropActivity.setupAspectRatioWidget(UCropActivity.java:431)
	at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:303)
	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:6285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class com.yalantis.ucrop.view.widget.AspectRatioTextView

**Comment by KucherenkoIhor** [comment]
@Hitexroid ,Hi
Did you try to pass other arguments to withAspectRatio function?

**Comment by rafalo1333** [comment]
@Yalantis @KucherenkoIhor Any plans of fixing this one? I am having problems with that excellent library on the older Android phone because of that bug.

**Comment by KucherenkoIhor** [comment]
Hi, @rafalo1333 did you try to pass other arguments to withAspectRatio function? Please, provide more info to reproduce this bug.

**Comment by rafalo1333** [comment]
I was using .withAspectRatio(16,9) and it works fine on all devices, only
old LG with 5.0.2 crashes...

26.08.2017 18:53 "Ihor Kucherenko" <notifications@github.com> napisał(a):

Hi, @rafalo1333 <https://github.com/rafalo1333> did you try to pass other
arguments to withAspectRatio function? Please, provide more info to
reproduce this bug.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Yalantis/uCrop/issues/273#issuecomment-325146229>, or mute
the thread

**Comment by KucherenkoIhor** [comment]
@rafalo1333 If you have ideas how to fix this error, you can make a pull request. We will glad to merge it.

**Comment by rafalo1333** [comment]
No I dont have any, I dont know the library code at all.

28.08.2017 10:09 "Ihor Kucherenko" <notifications@github.com> napisał(a):

**Comment by Hitexroid** [comment]
@KucherenkoIhor 

> Did you try to pass other arguments to withAspectRatio function?

yes , i still have this problem .

**Comment by KucherenkoIhor** [comment]
@rafalo1333, thank you. We will try to fix it as soon as possible.

**Comment by Legementarion** [comment]
Fixed at last release

**Comment by ShivamSavita** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paisalo.new_bc_app/com.yalantis.ucrop.UCropActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3887)
                 	
                 	
                 	i'm getting this can anyone help me
