### ISSUE TITLE
com.yalantis.ucrop.UCropActivity: java.lang.NullPointerException

### ISSUE THREAD

**Issue by anupdey99** [Yalantis/uCrop#342]
Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setBackgroundColor(int)' on a null object reference.

Where is the problem?

**Comment by anupdey99** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.yalantis.ucrop.UCropActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setBackgroundColor(int)' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setBackgroundColor(int)' on a null object reference
                                                                           at com.yalantis.ucrop.UCropActivity.setupAppBar(UCropActivity.java:310)
                                                                           at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:276)
                                                                           at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:111)
                                                                           at android.app.Activity.performCreate(Activity.java:6303)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by anupdey99** [comment]
compileSdkVersion 26
    buildToolsVersion '26.0.1'

**Comment by anupdey99** [comment]
Ok, I solve the issue.

**Comment by anupdey99** [comment]
The issue was somehow Library _toolbar id_ is same as another _toolbar id_.
A refactor rename causes the issue. 
But why refactor rename access & modify the library files!!!!!

**Comment by vatsmanu** [comment]
how did you resolve the issue ?
