### ISSUE TITLE
SecurityException on Android 7.0

### ISSUE THREAD

**Issue by Jeff11** [Yalantis/uCrop#350]
**What is the current behavior?**
App crashes for a hand full of users with Samsung, Huawei, Motorola on Android 7.0

**Which versions of uCrop, and which Android API versions are affected by this issue?**
uCrop 2.2.1

> Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.impl.MediaContentProvider from ProcessRecord{67fed2a 11719:com.myapp/u0a234} (pid=11719, uid=10234) that is not exported from uid 10189
       at android.os.Parcel.readException(Parcel.java:1693)
       at android.os.Parcel.readException(Parcel.java:1646)
       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4912)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:6043)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2474)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1521)
       at android.content.ContentResolver.query(ContentResolver.java:520)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at com.yalantis.ucrop.util.FileUtils.getDataColumn(FileUtils.java:109)
       at com.yalantis.ucrop.util.FileUtils.getPath(FileUtils.java:194)
       at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:171)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by yc654084303** [comment]
me to

**Comment by Legementarion** [comment]
@Jeff11 @yc654084303  Please check out last ucrop version and report please, bug still reproduce?

**Comment by Jeff11** [comment]
I can't find this crash anymore in the last 90 days.

**Comment by Legementarion** [comment]
@Jeff11 So, it solved? )

**Comment by Legementarion** [comment]
Fixed

**Comment by waseefakhtar** [comment]
I receive a similar crash from a user on OnePlus5 using Android 9: 

```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:354)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.SecurityException: 
  at android.os.Parcel.createException (Parcel.java:1950)
  at android.os.Parcel.readException (Parcel.java:1918)
  at android.os.Parcel.readException (Parcel.java:1868)
  at android.app.IActivityManager$Stub$Proxy.getContentProvider (IActivityManager.java:4129)
  at android.app.ActivityThread.acquireProvider (ActivityThread.java:6164)
  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider (ContextImpl.java:2641)
  at android.content.ContentResolver.acquireUnstableProvider (ContentResolver.java:1963)
  at android.content.ContentResolver.query (ContentResolver.java:831)
  at android.content.ContentResolver.query (ContentResolver.java:762)
  at android.content.ContentResolver.query (ContentResolver.java:720)
  at com.yalantis.ucrop.util.FileUtils.getDataColumn (FileUtils.java:110)
  at com.yalantis.ucrop.util.FileUtils.getPath (FileUtils.java:202)
  at com.yalantis.ucrop.task.BitmapLoadTask.getFilePath (BitmapLoadTask.java:194)
  at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri (BitmapLoadTask.java:174)
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground (BitmapLoadTask.java:93)
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground (BitmapLoadTask.java:44)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
Caused by: android.os.RemoteException: 
  at com.android.server.am.ActivityManagerService.getContentProviderImpl (ActivityManagerService.java:13896)
  at com.android.server.am.ActivityManagerService.getContentProvider (ActivityManagerService.java:14312)
  at android.app.IActivityManager$Stub.onTransact (IActivityManager.java:357)
  at com.android.server.am.ActivityManagerService.onTransact (ActivityManagerService.java:3820)
  at android.os.Binder.execTransact (Binder.java:752)
```

I'm currently running version 2.2.3.
