### ISSUE TITLE
 Skipping AppWindowToken   com.yalantis.ucrop.UCropActivity t1074

### ISSUE THREAD

**Issue by linuxhsj** [Yalantis/uCrop#395]
`I/BitmapCropTask: Should crop: true
W/ExifInterface: Invalid image.
                 java.io.IOException: Invalid marker: 89
                     at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1627)
                     at android.media.ExifInterface.loadAttributes(ExifInterface.java:1353)
                     at android.media.ExifInterface.<init>(ExifInterface.java:1070)
                     at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:150)
                     at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:94)
                     at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:35)
                     at android.os.AsyncTask$2.call(AsyncTask.java:307)
                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                     at java.lang.Thread.run(Thread.java:833)
V/FA: Recording user engagement, ms: 1522
V/WindowManager: Skipping AppWindowToken{84b15fb token=Token{ba7bb8a ActivityRecord{18651f5 u0 com.linux.demo/com.yalantis.ucrop.UCropActivity t1074}}} -- going to hide` @Lx @sfes @jasl @edBaev 

Taking pictures directly or selecting photos from an album will report the above error log. My mobile phone is huawei KIW-CL00. Can you help me see this problem? Thank you in advance.

**Comment by Lx** [comment]
@linuxhsj, I don't understand why you have tagged me in this issue as I'm not a uCrop developer.

Nonetheless, it looks like a problem with the EXIF data in the specific image you've selected.  If you upload that image to this ticket, it might assist the developers in handling certain cases of images having corrupted EXIF data.

**Comment by Legementarion** [comment]
@linuxhsj I think @Lx is right. Please share your image as example

**Comment by Legementarion** [comment]
So unclear, Think, you had use corrupted image
