### ISSUE TITLE
Add feature to continue cropping based on the last edit

### ISSUE THREAD

**Issue by azri92** [Yalantis/uCrop#412]
**As of v 2.2.2**, uCrop does not:
1. return information of _last state_ when cropping
2. accept info of _saved state_ and lay out views based on the the provided state.

**The goal** is to enable users to **continue editing** the same **image that was already edited** based on the last saved state.

### **Ideas for this**
Saved state to be returned post-crop should include:
1. Image matrix.
2. Crop rect.

To continue editing:
1. Have a _withSavedStateOption(matrix, cropRect)_ in uCrop intent builder.
2. In _CropImageView.onImageLaidOut()_, set up using saved state info provided if available.

**Comment by azri92** [comment]
I do notice that cropOffsetX & cropOffsetY are provided but I'm not sure how to use these (and if they're sufficient to rebuild state).

**Comment by maxtracking** [comment]
@Legementarion It looks like with a bit of hacking it's possible to restore the cropping state. What I've done so far:
- aliased UCrop's layout so mine contains 2 custom views that inherit from gesture and overlay views in UCrop
- when user goes away from particular ```UCropView``` (and I have a number of images in my activity) I save gesture view's matrix
- when I want to restore, I set this matrix back in ```onImageLaidOut()```

The only problem with above is that I cannot easily reset overlay's rectangle. Any ideas?

**Comment by azri92** [comment]
@maxtracking Maybe you can check out this PR (on a forked version):
https://github.com/photobook-worldwide-mobile/uCrop/pull/1

@Legementarion let me know if you would like me to create a direct PR to this repo.

**Comment by maxtracking** [comment]
@azri92 Thanks, I will have a look.

**Comment by jonathanlip1100** [comment]
@azri92 
https://github.com/photobook-worldwide-mobile/uCrop
I run your demo and get error below
`java.lang.NullPointerException: Attempt to read from field 'float com.yalantis.ucrop.model.BleedPercentage.left' on a null object reference
        at com.yalantis.ucrop.view.OverlayView.drawBleedRects(OverlayView.java:569)
        at com.yalantis.ucrop.view.OverlayView.onDraw(OverlayView.java:390)
        at android.view.View.draw(View.java:21473)`

Can you fix  it. thanks
