### ISSUE TITLE
onFailure: setImageUri - ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by jhohannespurba** [Yalantis/uCrop#426]
getting this message for some image, and request code 69

TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:210)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Legementarion** [comment]
@jhohannespurba Hello! Could you please show some example of uri which you provide to ucrop?

**Comment by jhohannespurba** [comment]
src : content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F69/ORIGINAL/NONE/1699355053 
    Filename:1699355053 
    destination: /storage/emulated/0/aksara_batak/bg_1528257975630.png

i get this error too:

06-06 11:06:16.584 9990-10009/batak.aksara.com.aksarabatak E/BitmapWorkerTask: Copying failed
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:210)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jhohannespurba** [comment]
after change ACTION_PICK to ACTION_GET_CONTENT, now is working.

Intent intent = new Intent(Intent.ACTION_GET_CONTENT, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);

Thankyou

**Comment by sleepstream** [comment]
Everything is working, but still have error:

different code:

`Intent chooseImageIntent = new Intent(Intent.ACTION_GET_CONTENT, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
startActivityForResult(chooseImageIntent, PICK_IMAGE_ID);`
OR
`Intent chooseImageIntent = ImagePicker.getPickImageIntent(context);`


onActivityResult:
`String filepath = Environment.getExternalStorageDirectory()+"/project/storeImage/IMG_"+currentInvoice.store.place_id + ".png";
String path = Environment.getExternalStorageDirectory()+"/PriceKeeper/storeImage/";
                File file = new File(path);
                file = new File(filepath);
                Uri destinationUri = Uri.parse(file.toURI().toString());
                Uri sourceUri = Uri.parse(file.toURI().toString());
                UCrop.Options options = new UCrop.Options();
                options.setFreeStyleCropEnabled(true);
                options.setAllowedGestures(UCropActivity.SCALE, UCropActivity.SCALE, UCropActivity.SCALE);
                options.setHideBottomControls(true);
                options.setAspectRatioOptions(0, new AspectRatio("16x4", 16, 4));
                UCrop.of(sourceUri, destinationUri)
                        .withOptions(options)
                        .start((Activity) context);`

**Comment by didikee** [comment]
```
outputStream = new FileOutputStream(new File(outputUri.getPath()));
```
`uri.getPath()` maybe invalid for normal file system.

**Comment by didikee** [comment]
2019-04-19 17:33:41.102 30601-31181/com.didikee.photo.compress E/BitmapWorkerTask: Copying failed
 java.io.FileNotFoundException: /external_files/Pictures/PhotoLite/Jietu20190406-182404@2x.png (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:211)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-04-19 17:33:41.105 30601-30601/com.didikee.photo.compress D/ViewRootImpl@c41af5e[UCropActivity]: setView = DecorView@c1a7f3f[UCropActivity] TM=true MM=false
2019-04-19 17:33:41.119 30601-30601/com.didikee.photo.compress D/ViewRootImpl@c41af5e[UCropActivity]: dispatchAttachedToWindow
2019-04-19 17:33:41.137 30601-30601/com.didikee.photo.compress D/ViewRootImpl@c41af5e[UCropActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3489740800} changed=true
2019-04-19 17:33:41.145 30601-30669/com.didikee.photo.compress D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
2019-04-19 17:33:41.145 30601-30669/com.didikee.photo.compress D/OpenGLRenderer: eglCreateWindowSurface = 0xe8592c50
2019-04-19 17:33:41.152 30601-30601/com.didikee.photo.compress E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: /external_files/Pictures/PhotoLite/Jietu20190406-182404@2x.png (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:211)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```
/external_files/Pictures/PhotoLite/Jietu20190406-182404@2x.png (No such file or directory)
```
`/external_files/` is invalid.
The correct file path like `/storage/emulated/0/Pictures/PhotoLite/Jietu20190406-182404@2x.png`
