### ISSUE TITLE
Downloading failed  java.io.FileNotFoundException: No such file or directory

### ISSUE THREAD

**Issue by sleepstream** [Yalantis/uCrop#432]
`Downloading failed
                                                                               java.io.FileNotFoundException: No such file or directory
                                                                                   at android.os.Parcel.openFileDescriptor(Native Method)
                                                                                   at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:252)
                                                                                   at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:198)
                                                                                   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:922)
                                                                                   at android.content.ContentResolver.openOutputStream(ContentResolver.java:692)
                                                                                   at android.content.ContentResolver.openOutputStream(ContentResolver.java:668)
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:250)
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:168)
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:864)
06-07 16:20:52.877 21886-21886/com.sleepstream.checkkeeper E/TransformImageView: onFailure: setImageUri
                                                                                 java.io.FileNotFoundException: No such file or directory
                                                                                     at android.os.Parcel.openFileDescriptor(Native Method)
                                                                                     at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:252)
                                                                                     at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:198)
                                                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:922)
                                                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:692)
                                                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:668)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:250)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:168)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
                                                                                     at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:864)`

Trying to start on android 4.4.2
HTC One
'com.github.yalantis:ucrop:2.2.2'

On another device the same code work perfect.

**Comment by sleepstream** [comment]
Sorry, It's my error.
`Uri destinationUri = Uri.parse(file.toURI().toString());

                    UCrop.Options options = new UCrop.Options();
                    options.setFreeStyleCropEnabled(true);
                    options.setAllowedGestures(UCropActivity.SCALE, UCropActivity.SCALE, UCropActivity.SCALE);
                    options.setHideBottomControls(true);
                    options.setAspectRatioOptions(0, new AspectRatio("16x4", 16, 4));
                    UCrop.of(sourceUri, destinationUri)
                            .withOptions(options)
                            .withMaxResultSize(1100, 340)
                            .start((Activity) context);`


Didn't check file  in destinationUri  for existing.

**Comment by ag2m** [comment]
this is my problem too

**Comment by veled** [comment]
same problem with api 27 and 28 devices

E/BitmapWorkerTask: Downloading failed
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1290)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1055)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1031)
        at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:238)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:165)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1290)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1055)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1031)
        at com.yalantis.ucrop.task.BitmapLoadTask.downloadFile(BitmapLoadTask.java:238)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:165)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
