### ISSUE TITLE
 android.view.InflateException

### ISSUE THREAD

**Issue by Petrulak** [Yalantis/uCrop#44]
Hello guys, I am trying to integrate you cropping tool which looks pretty amazing into our app.
Unfortunately  iam experiencing " android.view.InflateException" after i call :
```java
UCrop.of(uri, mDestinationUri)
      .withAspectRatio(1, 1)
      .withMaxResultSize(Constants.CROP_IMAGE_MAX_SIZE, Constants.CROP_IMAGE_MAX_SIZE)
      .start(this);
```
with : 
```
uri : content://com.android.providers.media.documents/document/image%3A31397
mDestinationUri : file:///data/data/com.our.package.name.debug/cache/SampleCropImage.jpeg 
```
error looks like this :
```sh
Process: com.our.package.name.debug, PID: 757
                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.our.package.name.debug/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #40: Error inflating class <unknown>
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:135)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                 Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class <unknown>
                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                    at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:91)
                                                    at android.app.Activity.performCreate(Activity.java:5990)
                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:135) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                    at java.lang.reflect.Constructor.newInstance(Native Method)
                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                    at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:91) 
                                                    at android.app.Activity.performCreate(Activity.java:5990) 
                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:135) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=20; index=1882
                                                    at android.content.res.StringBlock.get(StringBlock.java:65)
                                                    at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
                                                    at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:991)
                                                    at android.content.res.TypedArray.getString(TypedArray.java:176)
                                                    at android.widget.TextView.<init>(TextView.java:1015)
                                                    at android.widget.TextView.<init>(TextView.java:632)
                                                    at com.yalantis.ucrop.view.widget.AspectRatioTextView.<init>(AspectRatioTextView.java:44)
                                                    at com.yalantis.ucrop.view.widget.AspectRatioTextView.<init>(AspectRatioTextView.java:40)
                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                    at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:91) 
                                                    at android.app.Activity.performCreate(Activity.java:5990) 
                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:135) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by shliama** [comment]
That's really strange. Have you modified the library or used maven dependency?
Anyway please check whether you have any significant differences with the sample.

**Comment by Petrulak** [comment]
Hello, i did not modified lib. Just added it to Gradle file and than tried to run sample. Unfortunately iam getting above error and i iam running out our ideas how to fix it .

**Comment by DavzorD** [comment]
@Petrulak Did you fix it ? I got the same weird bug

**Comment by shliama** [comment]
The issue was fixed: https://github.com/Yalantis/uCrop/issues/62
