### ISSUE TITLE
FileProvider URI's result in FileNotFoundException: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by hhoang** [Yalantis/uCrop#448]
Having trouble using UCrop 2.2.2 with FileProvider URI's.
This is only an issue if the destinationFile comes from a FileProvider.
Running 8.1.0 on Pixel 

08-09 14:58:43.019 18052-18052/com.dfs.fds E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1242)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1100)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1054)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:100)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by JieGenius** [comment]
I also had this problem，How did you solve it?

**Comment by Anubhavchoudhary009** [comment]
how did you solve it m stuck to

**Comment by gbirk** [comment]
Any updates?

**Comment by hhoang** [comment]
Sorry, it's been a while since I looked at this issue. But the problem seemed to have been caused by how we were using the library. To resolve the issue, I refactored our code to pass the desired destination URI to the UCrop library, rather than receiving the URI from a result.


After we take a picture with the camera, we take the source image and create a second file to store the cropped image, then pass both the source URI as well as the intended destination URI to UCrop.
` val uCrop = UCrop.of(sourceURI, Uri.fromFile(it))
          .withOptions(options)
          .withAspectRatio(1f, 1f)
          .withMaxResultSize(450, 450)

      uCrop.start(this)`

**Comment by vincent-paing** [comment]
Still having this issue, Here's the code I use to get the output uri

```
 val imageDir = context.cacheDir
    val image = File(imageDir, "cropped.jpg")
    image.createNewFile()

    val outputUri =
      FileProvider.getUriForFile(
        context,
        context.getString(R.string.file_provider_authorities),
        image
      )
```

**Comment by yooeunyeoul** [comment]
> Still having this issue, Here's the code I use to get the output uri
> 
> ```
>     val imageDir = context.cacheDir
>     val image = File(imageDir, "cropped.jpg")
>     image.createNewFile()
> 
>     val outputUri =
>       FileProvider.getUriForFile(
>         context,
>         context.getString(R.string.file_provider_authorities),
>         image
>       )
> ```

thank you , it works!!

**Comment by raveesh08** [comment]
I too faced same issue today.
U should use` Uri.fromFile(ur_file_object)`
But when analysed the issue I was able to trace that Uri returned by `Uri.fromFile` and `FileProvder` are different
One returns as file:/// and another with content:// 
Android 7.0 onwards using file provider is recommended I guess....
But still u can use ` Uri.fromFile(ur_file_object)`
I think library works great with file:/// but when content:// uri is given it fails because it unable to resolve the path from content uri
It ll be good if function call are given one for file and another for provider. Going forward it's required
