### ISSUE TITLE
ExifInterface got an unsupported image format file

### ISSUE THREAD

**Issue by MRezaNasirloo** [Yalantis/uCrop#458]
**Do you want to request a *feature* or report a *bug*?**
Bug report
**What is the current behavior?**
Undefined
**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
Android 7.0 Galaxy A7 2016 - latest ucrop version
```
I/BitmapCropTask: Should crop: true
2018-10-14 15:20:28.800 18386-19902/com.foo.internal I/ExifInterface_JNI: Raw image not detected
2018-10-14 15:20:28.800 18386-19902/com.foo.internal W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
        at android.media.ExifInterface.<init>(ExifInterface.java:1112)
        at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:151)
        at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:95)
        at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:35)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
2018-10-14 15:20:28.807 18386-19902/com.foo.internal I/ExifInterface_JNI: Raw image not detected
```
Looks like #367 didn't fix this

**Comment by p1nkydev** [comment]
@MRezaNasirloo You must to use supported format of images.
