### ISSUE TITLE
Error after selecting image to crop

### ISSUE THREAD

**Issue by dennykurniawan48** [Yalantis/uCrop#521]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
after selecting image, its show runtime error
**What is the expected behavior?**
after selecting image, its redirect to crop activity
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`android.content.res.Resources$NotFoundException: File res/drawable/ucrop_ic_cross.xml from drawable resource ID #0x7f07009b`
**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
 ```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.delusionsoftware.wishlistapp/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ucrop_ic_cross.xml from drawable resource ID #0x7f07009b
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ucrop_ic_cross.xml from drawable resource ID #0x7f07009b
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:465)
        at com.yalantis.ucrop.UCropActivity.setupAppBar(UCropActivity.java:345)
        at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:296)
        at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:125)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5019) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:465) 
        at com.yalantis.ucrop.UCropActivity.setupAppBar(UCropActivity.java:345) 
        at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:296) 
        at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:125) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5019) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by boldijar** [comment]
Also happens for me, on android 19.

**Comment by 3azvar** [comment]
Also for me

**Comment by boldijar** [comment]
I fixed it by adding 
```
static
{
    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}
```

In Application class.

**Comment by 3azvar** [comment]
ok , This answer is correct
Thanks.


در تاریخ دوشنبه ۲۲ آوریل ۲۰۱۹،‏ ۱۷:۴۱ Boldijar Paul <
notifications@github.com> نوشت:

**Comment by isaacfi** [comment]
@boldijar can you show the complete Application class, it is because I have the same issue in flutter, and I want to override the FlutterApplication class.

Regards
