### ISSUE TITLE
How can I display a placeholder into ImageView from a drawable resource before taking photo or picking photo?

### ISSUE THREAD

**Issue by ldt25290** [Yalantis/uCrop#557]
How can I display a placeholder into ImageView from a drawable resource before taking photo or picking photo?

I have an image in drawable folder default_avatar.png
Then I configured UCrop:
```
 private fun configUCrop(): UCrop {
        val destinationFileName = "sample_image"

        val sourceUri = getUriFromDrawable(this, R.drawable.default_avatar)
        val destinationUri = Uri.fromFile(File(cacheDir, destinationFileName))

        val uCrop = UCrop.of(sourceUri, destinationUri).withAspectRatio(1f, 1f)
        val options = UCrop.Options()
        options.setCompressionFormat(Bitmap.CompressFormat.PNG)
        options.setCompressionQuality(90)
        options.setCircleDimmedLayer(true)
        options.setShowCropGrid(false)
        options.setShowCropFrame(false)

        options.setHideBottomControls(true)
        options.setLogoColor(ContextCompat.getColor(this, R.color.black))

        uCrop.withOptions(options)

        return uCrop
    }
```
```
 private fun getUriFromDrawable(context: Context, @DrawableRes resId: Int): Uri {
     val resources = context.resources
     return Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + resources.getResourcePackageName(resId) + '/'.toString() + resources.getResourceTypeName(resId) + '/'.toString() + resources.getResourceEntryName(resId))
}
```
But the app crashes and this is log:
```
 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.dt.testprojectnew, PID: 10518
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalArgumentException: Invalid Uri schemeandroid.resource
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:187)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```
Please help! Thanks!

**Comment by TermLog** [comment]
There is no such feature to set a placeholder. The `sourceUri` should be a web link or URI of the existing file.
