### ISSUE TITLE
issue about toolbar

### ISSUE THREAD

**Issue by grantonzhuang** [Yalantis/uCrop#58]
a new issue comes up when update to `1.3.1` version
```
 Caused by: java.lang.IllegalStateException: 
This Activity already has an action bar supplied by the window decor. 
Do not request Window.FEATURE_SUPPORT_ACTION_BAR 
and set windowActionBar to false in your theme to use a Toolbar instead.
at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:195)
                                                                       at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:119)
                                                                       at com.yalantis.ucrop.UCropActivity.setupAppBar(UCropActivity.java:268)
                                                                       at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:239)
                                                                       at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:101)
                                                                       at android.app.Activity.performCreate(Activity.java:6251)
```

it seems here:
```
private void setupAppBar() {
        setStatusBarColor(mStatusBarColor);

        final Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);

        // Set all of the Toolbar coloring
        toolbar.setBackgroundColor(mToolbarColor);
        toolbar.setTitleTextColor(mToolbarTextColor);

        final TextView toolbarTitle = (TextView) toolbar.findViewById(R.id.toolbar_title);
        toolbarTitle.setTextColor(mToolbarTextColor);
        toolbarTitle.setText(mToolbarTitle);

        // Color buttons inside the Toolbar
        Drawable stateButtonDrawable = ContextCompat.getDrawable(this, R.drawable.ucrop_ic_cross).mutate();
        stateButtonDrawable.setColorFilter(mToolbarTextColor, PorterDuff.Mode.SRC_ATOP);
        toolbar.setNavigationIcon(stateButtonDrawable);

        setSupportActionBar(toolbar);// here
        final ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayShowTitleEnabled(false);
        }
    }
```

**Comment by grantonzhuang** [comment]
oh, I sloved using code following:
```
<activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar" />
```
