### ISSUE TITLE
EACCES (Permission denied)

### ISSUE THREAD

**Issue by vistech756** [Yalantis/uCrop#603]
I am passing the image uri that i have got by requesting the image picker. And then app crashes.

<code> else if (requestCode == PERMISSION_PICK_IMAGE_FOR_CROP) {
                if (data.getData() != null) {
                    String destinationFileName = new StringBuilder(UUID.randomUUID().toString()).append(".jpg").toString();
                    UCrop uCrop = UCrop.of(data.getData(), Uri.fromFile(new File(getCacheDir(), destinationFileName)));
                    uCrop.start(SelectionActivity.this);
                }
            } </code>

This is the stack trace:

<code>E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1345)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1293)
        at com.yalantis.ucrop.task.a.a(SourceFile:100)
        at com.yalantis.ucrop.task.a.doInBackground(SourceFile:44)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)</code>

Device : S10+
Api level : 29

**Comment by guiguito** [comment]
i'm currently facing the same issue in production.

**Comment by guiguito** [comment]
This stackoverflow helped me workaround this issue.
https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android/57804657#57804657

**Comment by joker-fu** [comment]
#606

**Comment by Marina24** [comment]
Issue has been already opened - #603
