### ISSUE TITLE
Crash after photo selection

### ISSUE THREAD

**Issue by DavzorD** [Yalantis/uCrop#62]
When I select the photo and try to load the cropActivity, I got an error. Don't know what to do!

**Call** 
_In fragment_ 

``` Java
public void CropImage(Uri selectedImage) {
    UCrop.Options options = new UCrop.Options();
    options.setToolbarColor(ContextCompat.getColor(getContext(), R.color.ocean_blue));
    options.setCompressionFormat(Bitmap.CompressFormat.PNG);
    UCrop.of(selectedImage, Uri.fromFile(new File(getContext().getFilesDir(), "image.png")))
      .withAspectRatio(1, 1)
      .withMaxResultSize(800, 800)
      .withOptions(options)
      .start(getContext(), this );
  }
```

selectedImage URI = content://com.android.providers.media.documents/document/image%3A190
newFile URI = file:///data/data/app.speaky.com/files/image.png

**Error stack** 

```
 03-16 14:12:10.864 16502-16502/? E/AndroidRuntime: FATAL EXCEPTION: main
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime: Process: app.speaky.com, PID: 16502
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.speaky.com/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #40: Error inflating class <unknown>
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:177)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:  Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class <unknown>
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:633)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:97)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6178)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:177) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:97) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6178) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:177) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=20; index=1872
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.content.res.StringBlock.get(StringBlock.java:65)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:482)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1003)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.content.res.TypedArray.getString(TypedArray.java:177)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.widget.TextView.<init>(TextView.java:1087)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.widget.TextView.<init>(TextView.java:685)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.yalantis.ucrop.view.widget.AspectRatioTextView.<init>(AspectRatioTextView.java:44)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.yalantis.ucrop.view.widget.AspectRatioTextView.<init>(AspectRatioTextView.java:40)
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:97) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6178) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:177) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
03-16 14:12:10.864 16502-16502/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
```

**Gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId 'app.speaky.com'
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName '1.0'
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:support-v4:23.2.0'
    compile 'com.joanzapata.iconify:android-iconify-fontawesome:2.1.1'
    compile 'com.joanzapata.iconify:android-iconify-material:2.1.1'
    compile 'com.android.support:design:23.2.0'
    compile 'com.android.support:recyclerview-v7:23.2.0'
    compile 'com.android.support:cardview-v7:23.2.0'
    compile 'com.makeramen:roundedimageview:2.2.1'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.okhttp:okhttp:2.7.0'
    compile 'com.facebook.android:facebook-android-sdk:4.9.0'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'org.jetbrains:annotations:13.0'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'com.google.guava:guava:19.0'
    compile('io.socket:socket.io-client:0.7.0') {
        exclude group: 'org.json', module: 'json'
    }
    compile 'org.apmem.tools:layouts:1.10'
    compile 'com.yalantis:ucrop:1.3.2'
    compile 'org.webjars:google-diff-match-patch:20121119-1'
    compile 'joda-time:joda-time:2.9.2'
    compile 'com.github.rahatarmanahmed:circularprogressview:2.4.0'
}

apply plugin: 'com.google.gms.google-services'

**Comment by shliama** [comment]
I guess there is something wrong with a Theme.

Try to define theme for UCropActivity

```xml
<style name="AppTheme.UCropTheme" parent="Theme.AppCompat.Light.NoActionBar"/>
```
 and set it in your AndroidManifest

```xml
<activity
 android:name="com.yalantis.ucrop.UCropActivity"
 android:screenOrientation="portrait"
 android:theme="@style/AppTheme.UCropTheme"/>
```

**Comment by DavzorD** [comment]
Ok, it's working fine now!
Thank you so much, was stuck on this one for ages!

**Comment by shliama** [comment]
Glad it helped :+1: I think I should update a Readme
