### ISSUE TITLE
Getting Crash of IndexOutOfBoundsException in ImageHeaderParser.java Class.

### ISSUE THREAD

**Issue by MihirAhir** [Yalantis/uCrop#640]
I can't generate this crash but i'm getting this crash in crashlytics.

**Comment by knaoe** [comment]
Me too in v2.2.4 and Android 6.0.1

```
Caused by java.lang.IndexOutOfBoundsException: index=14, limit=14, size of type=2
       at java.nio.Buffer.checkIndex(Buffer.java:159)
       at java.nio.ByteArrayBuffer.getShort(ByteArrayBuffer.java:234)
       at com.yalantis.ucrop.util.ImageHeaderParser$RandomAccessReader.getInt16(ImageHeaderParser.java:309)
       at com.yalantis.ucrop.util.ImageHeaderParser.parseExifSegment(ImageHeaderParser.java:209)
       at com.yalantis.ucrop.util.ImageHeaderParser.parseExifSegment(ImageHeaderParser.java:120)
       at com.yalantis.ucrop.util.ImageHeaderParser.getOrientation(ImageHeaderParser.java:103)
       at com.yalantis.ucrop.util.BitmapLoadUtils.getExifOrientation(BitmapLoadUtils.java:77)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:143)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by ChengCheng-Hello** [comment]
Android 10
Caused by: java.lang.IndexOutOfBoundsException: index=134217734 out of bounds (limit=104, nb=2)
	at java.nio.Buffer.checkIndex(Buffer.java:564)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:263)
	at com.yalantis.ucrop.util.ImageHeaderParser$RandomAccessReader.getInt16(ImageHeaderParser.java:308)
	at com.yalantis.ucrop.util.ImageHeaderParser.parseExifSegment(ImageHeaderParser.java:208)
	at com.yalantis.ucrop.util.ImageHeaderParser.parseExifSegment(ImageHeaderParser.java:119)
	at com.yalantis.ucrop.util.ImageHeaderParser.getOrientation(ImageHeaderParser.java:102)
	at com.yalantis.ucrop.util.BitmapLoadUtils.getExifOrientation(BitmapLoadUtils.java:74)
	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:143)
	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
