### ISSUE TITLE
java.io.FileNotFoundException: open failed: EACCES (Permission denied) for Android 10 and upper

### ISSUE THREAD

**Issue by harrynguyen2k2** [Yalantis/uCrop#642]
I'm working on an android project using uCrop version 2.2.4, when it run on android Pie (api 28) and lower, It work very well, but when I test on android 10 and upper, It can't cut image from gallery  but Camera does well, when it  open uCrop Activity it close immediately. 

### This is the error log:
2020-04-28 17:07:35.477 28598-28598/com.harry.project E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1345)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1293)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:100)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by anjanaps** [comment]
Hey, I have a similar problem. How did you solve this problem
