### ISSUE TITLE
[bug] Runtime failure

### ISSUE THREAD

**Issue by mpowloka** [Yalantis/uCrop#702]
uCrop version: 2.2.6
The bug occurs on at least two devices: OnePlus 5T and some LG phone.

I am using an image_cropper plugin for Flutter, but the error itself is thrown inside UCropActivity. What is even weirder, my app works for an image taken by a camera and fails this way for a taken screenshot. I attach working and failing jpegs.

`E/AndroidRuntime(15029): FATAL EXCEPTION: main
E/AndroidRuntime(15029): Process: com.plantsandpots.dev, PID: 15029
E/AndroidRuntime(15029): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.plantsandpots.dev/com.yalantis.ucrop.UCropActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(15029): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3375)
E/AndroidRuntime(15029): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
E/AndroidRuntime(15029): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(15029): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15029): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15029): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
E/AndroidRuntime(15029): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15029): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(15029): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime(15029): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15029): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(15029): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(15029): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(15029): 	at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(Unknown Source:7)
E/AndroidRuntime(15029): 	at android.app.Application.dispatchActivityCreated(Application.java:407)
E/AndroidRuntime(15029): 	at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
E/AndroidRuntime(15029): 	at android.app.Activity.onCreate(Activity.java:1475)
E/AndroidRuntime(15029): 	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
E/AndroidRuntime(15029): 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:149)
E/AndroidRuntime(15029): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:313)
E/AndroidRuntime(15029): 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
E/AndroidRuntime(15029): 	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:125)
E/AndroidRuntime(15029): 	at android.app.Activity.performCreate(Activity.java:7815)
E/AndroidRuntime(15029): 	at android.app.Activity.performCreate(Activity.java:7804)
E/AndroidRuntime(15029): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
E/AndroidRuntime(15029): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
E/AndroidRuntime(15029): 	... 11 more
I/Process (15029): Sending signal. PID: 15029 SIG: 9
Lost connection to device.`

Failing example:
![failing_example](https://user-images.githubusercontent.com/27731000/92235851-ab149c00-eeb4-11ea-8d30-f8d11bae8808.jpeg)

Working example:
![working_example](https://user-images.githubusercontent.com/27731000/92235857-ac45c900-eeb4-11ea-8501-eeaa7a549b7d.jpeg)

**Comment by mpowloka** [comment]
It occurred to be a problem with a different library.
