### ISSUE TITLE
BitmapLoadTask.java line 179

### ISSUE THREAD

**Issue by sauniksingh** [Yalantis/uCrop#731]
**Do you want to report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`Caused by java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/191991
       at android.os.Parcel.createException(Parcel.java:2079)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:705)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
       at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:179)
       at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:158)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:87)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:36)
       at android.os.AsyncTask$3.call(AsyncTask.java:389)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)`

UCrop Version: **2.2.6-native**
Android API: **29**
Device: **P30 Pro**

**Comment by AxitaKathiriya** [comment]
Hi @sauniksingh,
Is this issue resolved in UCrop Version: 2.2.7?

I am using UCrop Version: 2.2.7 still I got this crash in my crashlytics in OS 10,11 & 12.
