### ISSUE TITLE
Canvas trying to load large size of image

### ISSUE THREAD

**Issue by sauniksingh** [Yalantis/uCrop#740]
java.lang.RuntimeException: Canvas: trying to draw too large(290841740bytes) bitmap. at android.graphics.BaseCanvas.nDrawBitmap(Native method) at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:192) at android.graphics.Canvas.drawBitmap(Canvas.java:1660) at com.yalantis.ucrop.util.FastBitmapDrawable.draw(FastBitmapDrawable.java:41) at android.widget.ImageView.onDraw(ImageView.java:1444)

Still getting same issue if we're trying to crop image more than 4mb. in NOKIA 6.1, Android 10, & UCROP version 2.2.6

**Comment by vladbakalo** [comment]
@sauniksingh Issue was resolved in #648

**Comment by shanraisshan** [comment]
any update on this?
