### ISSUE TITLE
Unable to start activity ComponentInfo{com.package.demo/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView

### ISSUE THREAD

**Issue by JaspalsinhCodiot** [Yalantis/uCrop#793]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.package.demo/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
      
![Screenshot](https://user-images.githubusercontent.com/70935257/143047760-9c176aa4-c3cd-45f0-8d79-d55c1425ec7e.png)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
![Screenshot2](https://user-images.githubusercontent.com/70935257/143047887-28f5ae6b-3193-4cad-b236-195b143f2908.png)

**Comment by Arkuda** [comment]
Have some error,  and strange - on same Nexus 5x, with android 8.1.0 with 506.mb free space and 1.35 gb of ram, maybe that emulator ?

**Comment by Navil** [comment]
I have the same issue. Also with a Nexus 5X and Version 8.1.0. Maybe it is a automated Google Test device that is faulty?

**Comment by luckv** [comment]
I'm sure it's a google test device.
I have the same issue..
