### ISSUE TITLE
Unable to start activity ComponentInfo{com.example.app/com.yalantis.ucrop.UCropActivity}

### ISSUE THREAD

**Issue by Navil** [Yalantis/uCrop#798]
**Bug Report**

**I am running a production application and on few devices, the following error results in a crash.**

![image](https://user-images.githubusercontent.com/3436399/145557490-9d10e40c-63c0-407d-8f42-de30f4e4b959.png)

**I am using version 1.4.1 and Flutter 2.8. The error however also occured before upgrading Flutter to 2.8**

**Comment by luckv** [comment]
Seems the same of #793 
I'm using version 2.2.6 of the plugin and flutter 2.5.3
Seems this error comes from a google emulator

**Comment by RodolfoGS** [comment]
Same issue, same device (Nexus 5X) and same Android version (8.1.0)

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{__app_name__/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

![image](https://user-images.githubusercontent.com/870365/146486231-822a8ff1-35b4-426c-9cef-049d975ce770.png)

**Comment by achuinard** [comment]
This might be related to Android S? Are you targeting API 31+?

**Comment by fleuverouge** [comment]
Hi, I'm getting the same issue on Android 9, Oppo A59

build.graddle:

```
{
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        androidXCore = "1.0.2"
    }
```

**Comment by ted81** [comment]
Hi, I'm getting the same issue.
- OS versions: Android 12 (64%), Android 11 (35%), Android 10 (1%)
- compileSdk / targetSdk: 33 / 33

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxxx/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #29 in xxxxx:layout/ucrop_controls: Binary XML file line #49 in xxxxx:layout/ucrop_layout_rotate_wheel: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3628)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3873)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

Caused by android.view.InflateException: Binary XML file line #29 in xxxxx:layout/ucrop_controls: Binary XML file line #49 in xxxxx:layout/ucrop_layout_rotate_wheel: Error inflating class ImageView

Caused by android.view.InflateException: Binary XML file line #49 in xxxxx:layout/ucrop_layout_rotate_wheel: Error inflating class ImageView

Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f070284

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f070284
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:287)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:854)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:694)
       at android.content.res.Resources.loadDrawable(Resources.java:993)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
       at android.widget.ImageView.<init>(ImageView.java:209)
       at android.widget.ImageView.<init>(ImageView.java:190)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:73)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:206)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:125)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1569)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1620)
       at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1141)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1278)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1141)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
       at com.yalantis.ucrop.UCropActivity.setupViews(UCropActivity.java:308)
       at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:130)
       at android.app.Activity.performCreate(Activity.java:8077)
       at android.app.Activity.performCreate(Activity.java:8061)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1315)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3601)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3873)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

**Comment by zynhrus** [comment]
> 

@RodolfoGS  Any update?

I got the error from crashlytics too and have the same device (Nexus 5X) and same Android version (8.1.0)

I try to reproduce it but it always works fine.

**Comment by zynhrus** [comment]
> Same issue, same device (Nexus 5X) and same Android version (8.1.0)
> 
> ```
> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{__app_name__/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
>        at android.app.ActivityThread.-wrap11()
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:164)
>        at android.app.ActivityThread.main(ActivityThread.java:6494)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> ```
> 
> ![image](https://user-images.githubusercontent.com/870365/146486231-822a8ff1-35b4-426c-9cef-049d975ce770.png)

@RodolfoGS Any update?

I got the error from crashlytics too and have the same device (Nexus 5X) and same Android version (8.1.0)

I try to reproduce it but it always works fine.

**Comment by iabdousd** [comment]
Same thing here, seeing the problem in Crashlytics and only happening to `Nexus 5x` devices with android `8.1.0`.

**Comment by Faiyyaz** [comment]
Same device and same android version and same issue is happening for me in an android native app using kotlin.

Ucrop version 2.2.9
