### ISSUE TITLE
Crash: java.lang.NoClassDefFoundError: android.support.v7.app.AppCompatDelegateImplV23 

### ISSUE THREAD

**Issue by WilliamQin7** [Yalantis/uCrop#83]
My gradle build is like this: compile 'com.yalantis:ucrop:1.4.1', and the error happens whether I add the support:appcompat-v7 or not.
Log:
java.lang.NoClassDefFoundError: android.support.v7.app.AppCompatDelegateImplV23
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:186)
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:170)
                                                                         at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:502)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:67)
                                                                         at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:101)
                                                                         at android.app.Activity.performCreate(Activity.java:6251)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by shliama** [comment]
I cannot reproduce this error on my several projects that use uCrop, so I do think it's something with your gradle config. Compare it with the sample - it works fine.
