### ISSUE TITLE
java.io.IOException: Failed to redact /storage/emulated/0/Pictures/xxx.jpg

### ISSUE THREAD

**Issue by wangjianpeng** [Yalantis/uCrop#830]
I found a crash from firebase console , which was happened on **samsung/Galaxy Tab A/Android 11**
```
Caused by java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalStateException: java.io.IOException: Failed to redact /storage/emulated/0/Pictures/WP_Blog_ES_Cover_Arc_Feb4-420x280.jpg
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1485)
       at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:179)
       at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:158)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:87)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:36)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Crop version :'com.github.yalantis:ucrop:2.2.6'**

**Comment by AxitaKathiriya** [comment]
Hi, I have also found a crash from firebase console , which was happened on **Samsung Galaxy Tab A7 - OS 11.**
I am using ucrop version : **2.2.7** 
Please do something and resolve this.

![Capture](https://user-images.githubusercontent.com/54742470/159840676-15a250c6-c704-4c8c-b90f-fb2e394e4a83.PNG)

**Comment by wangyongf** [comment]
any updates on this issue? thank you, I faced the same issue

**Comment by AkshayOptimumbrew** [comment]
any update on this issue?
I faced the same issue.
