### ISSUE TITLE
Bounds for bitmap could not be retrieved from Uri

### ISSUE THREAD

**Issue by saymumsany** [Yalantis/uCrop#834]
I am facing this issue while crop the image. I am using com.github.yalantis:ucrop:2.2.8 . I am facing this issue in Xiaomi Redmi note 8A device and some Realme devices.

2022-04-03 14:26:00.332 23053-23053/com.apps.main E/TransformImageView: onFailure: setImageUri
    java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [content://apps.main.provider/images/JPEG_20220403_142558_4239916797258029201.jpg]
        at wb.b.b(SourceFile:111)
        at wb.b.doInBackground(SourceFile:36)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Androbito** [comment]
same here!

**Comment by Jagadishvjr** [comment]
I am also facing same issue

**Comment by AkshayOptimumbrew** [comment]
same here

**Comment by ErZicky** [comment]
I know I'm late and I don't really have a code solution, but check the destination URI, if you're using the same uri for both source and destination it'll give that error, create a new uri for the destination
