### ISSUE TITLE
Caused by java.lang.IllegalArgumentException Invalid Uri schemenull in Android 11

### ISSUE THREAD

**Issue by PrudhviBanki** [Yalantis/uCrop#835]
I'm using latest 2.2.8-native

Devices : Samsung,OnePlus,Moto etc 

Caused by java.lang.IllegalArgumentException: Invalid Uri schemenull
       at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:166)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:88)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:37)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by mubasherhussain3** [comment]
imagePath = pics.get(position).picturePath
        val mFile = File(imagePath)
        val res_url = Uri.fromFile(mFile)

        UCrop.of(res_url, Uri.parse(outputFile.path)).start(requireActivity(),this@EditImageFragment)



use this syntax the it will work properly
