### ISSUE TITLE
Orientation issue while selecting image from camera

### ISSUE THREAD

**Issue by bivinFlyingSamurai** [Yalantis/uCrop#864]
> In a portrait Android App landscape camera image is taken, but after taking the pictured App is crashing, why because orientation changes happening from landscape to portrait. This issue I found in a Samsung device. Oneplus and pixel phones all working fine.

**Comment by bivinFlyingSamurai** [comment]
`19:43:39.530  E  onFailure: setImageUri
                 java.lang.IllegalArgumentException: Bitmap could not be decoded from the Uri: [content://com.weblogic.cnqrCreator.file%20Provider/cache/1669385619285.jpg]
                 	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:123)
                 	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:36)
                 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)
                 Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
                 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:342)
                 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:229)
                 	at androidx.core.content.FileProvider.openFile(FileProvider.java:632)
                 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:2138)
                 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2314)
                 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2381)
                 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:562)
                 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
                 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
                 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
                 	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:107)
                 	at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:36) 
                 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                 	at java.lang.Thread.run(Thread.java:1012) 
19:43:39.534  D  Focus request (0): cf37264 com.weblogic.cnqrCreator/com.yalantis.ucrop.UCropActivity but waiting because NOT_VISIBLE`

**Comment by bivinFlyingSamurai** [comment]
<activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:theme="@style/AppTheme.NoActionBar" />
        <activity
            android:name=".utils.ImagePickerActivity"
            android:exported="true"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait" />
